language: python
python:
  - "3.5"
  - "3.5-dev"  # 3.5 development branch
  - "3.6"
  - "3.6-dev"  # 3.6 development branch
  - "3.7-dev"  # 3.7 development branch
before_install:
 - bundle install
install:
  - "pip install pyaml flake8 pylint"
  - "pip install -U -r tests/requirements.txt"
script: "rake test"
